# action.yml
name: 'Rust Cargo Generate Rpm Package Build (amd64, OpenSUSELeap)'
description: 'Builds a rpm package, amd64, opensuse leap 16.0'
branding:
  icon: 'package'
  color: 'orange'
inputs:
  cmd:
    description: 'build command'
    required: true
    default: 'cargo build --release && cargo generate-rpm'
runs:
  using: 'docker'
  image: 'docker://jamesmcm03/cargo-rpm-amd64-opensuseleap:20260529'
  args:
    - ${{ inputs.cmd }}
