# action.yml
name: 'Rust Cargo Rpm Package Build (amd64, OpenSUSELeap)'
description: 'Builds a statically linked rpm package, amd64, musl, opensuse leap 15.1'
branding:
  icon: 'package'
  color: 'orange'
inputs:
  cmd:
    description: 'build command'
    required: true
    default: 'cargo rpm build -v'
runs:
  using: 'docker'
  image: 'docker://jamesmcm03/cargo-rpm-amd64-opensuseleap:20211220'
  args:
    - ${{ inputs.cmd }}
